posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    # Главная страница
    path('', views.index, name = 'home'),
    path('group/<slug:slug>/', views.group_posts, name = 'group'),
] 

yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace = 'posts')),
    path('admin/', admin.site.urls),
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.
User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length = 200)
    slug = models.SlugField(unique = True)
    description = models.TextField()

    def __str__(self):
        return self.title  

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add = True)
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'posts')
    group = models.ForeignKey(Group, blank = True, null = True, on_delete = models.SET_NULL)

posts/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Post, Group

def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    #output = []
    #for item in latest:
    #    output.append(item.text)
    #return HttpResponse('/n'.join(output))
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context) 

def group_posts(request, slug):
    # Функция get_object_or_404 получает по заданным критериям объект 
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)

    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'group.html', context) 

templates/base.html
{% load static %}

<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <title>
        {% block title %}
            Название сайта
        {% endblock %}
    </title>
  </head>
  <body>
    <header>
        {% include 'includes/header.html'%}
    </header>
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        {% block text %}
        Информация на странице группы будет тут.
        {% endblock %}
      </div>  
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отсупом сверху и снизу --> 
    <a href = {% url 'posts:home' %}> На главную </a>        
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html>

templates/group.html
{% extends 'base.html' %}

{% block title %}
    Записи сообщества {{ group.title }} | Yatube
{% endblock %}

{% block text %}
<h1>{{ group.title}}</h1>
{% for post in posts %}
<p> Дата публикации: {{ post.pub_date|date:"d M Y" }}</p>
<p>{{ post.text }}</p>  
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<p>{{ group.description }}</p> 
{% endblock %}

templates/includes/footer.html
<p>© 2020 Copyright <span style="color:red">Ya</span>tube</p> 

templates/includes/header.html
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      {% load static %}
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
           <!-- ссылка должна вести на главную страницу -->
          <a class="navbar-brand" href="">
            <img src="{% static "img/yatube.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>

templates/posts/group.html
<!-- templates/posts/index.htnl-->
{% extends 'base.html' %}

{% block title %}
Записи сообщества {{ group.title }}
{% endblock%}


{% block text %}
{% for post in posts %}
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date }}
  </li>
</ul>
<p>{{ post.text }}</p>    
{% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% endblock %}

templates/posts/index.html
<!-- templates/posts/index.html-->

{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock%}

{% block text %}
{% for post in posts %}
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
<p>{{ post.text }}</p>    
{% if post.group %}
    <a href="{% url 'posts:group' post.group.slug %}">{{ post.group.title }}</a>
{% endif %}
{% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% endblock %}